before_commands:
  - sudo pip3 install cleo
  - sudo pip3 install coverage

build:
  override:
    - command: coverage run -m unittest discover -s test -p *Test.py
      coverage:
        file: '.coverage'
        config_file: '.coveragerc'
        format: 'py-cc'

  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
