language: python
php:
  - '3.4'
  - '3.5'
  - '3.5-dev'
  - nightly
  
sudo: true

addons:
  mariadb: 10.1

before_install:
  - mysql --version
  - mysql -u root -e "create database if not exists test;"
  - mysql -u root -e "create user 'test'@'localhost' identified by 'test';"
  - mysql -u root -e "grant all on test.*  to 'test'@'localhost';"
  - mysql -u root -e "set global binlog_format = 'row';"
  - mysql -u root -e "set global log_bin_trust_function_creators = 1;"
  
install:
  - pip install pymssql
    
script: 
  cat test/mysql/ddl/create_tables.sql | mysql -utest -ptest test
  bin/stratum.py -c etc/mysql/test_stratum.cfg
  python3 -m unittest test/mysql/*.py
  

